services:
  frontend:
    image: jwpickup/garmintools-vue
    container_name: garmintools-vue-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    image: jwpickup/garmintools-server
    container_name: garmintools-java-backend
    ports:
      - "8080:8080"
